name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Git tag
        id: get_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vehicle-cli:${{ env.TAG_NAME }} .
 
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vehicle-cli:${{ env.TAG_NAME }}
