name: Vehicle Client CI

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.x'

      - name: Install Required Dependecies 
        run: npm ci

      - name: Check Node Version
        run: node --version

      - name: Build application
        run: npm run build
      # npm run postbuild is automatically executed via npm so no need to add it to CI
      
      - name: Run Lint for statistical analysis of the code 
        run: npm run lint

      - name: Run Tests
        run: npm run test-coverage

      - name: List dist output
        run: ls dist/

      # not necessary to build the project in Github Actions, but it will be used below
      - name: Install CLI Globally
        run: npm run global-install
        
      - name: Test if our CLI works as a global bash command when calling vehicle-cli
        run: vehicle-cli -h || echo 'Not yet'
